// <auto-generated />
namespace EcommerceOsorioManha.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Criando_DB_no_PC : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Criando_DB_no_PC));
        
        string IMigrationMetadata.Id
        {
            get { return "201808241128444_Criando_DB_no_PC"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
